# Generated by Django 4.2.7 on 2023-12-22 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic1', '0002_apointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('icon_class', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='apointment',
        ),
    ]
