# Generated by Django 4.2.7 on 2023-12-26 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic1', '0006_alter_doctor_facebook_link_alter_doctor_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('date', models.DateTimeField()),
                ('department', models.CharField(max_length=255)),
                ('doctor', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
