# Generated by Django 4.2.7 on 2023-12-26 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic1', '0007_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='department',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='phone',
            field=models.CharField(default='12', max_length=20),
        ),
    ]
