# Generated by Django 4.2.7 on 2023-12-27 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic1', '0008_alter_appointment_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
